config/routes.rb
Rails.application.routes.draw do
  resources :products 
  resources :taxons , only: %i[ show index]
  resources :users
  scope "(:locale)", locale: /en|vi/ do
    devise_scope :user  do
      get "user/signin" => "devise/sessions#new"
      post "user/signin" => "devise/sessions#create"
      delete "user/signout" => "devise/sessions#destroy"
    end

    namespace :admin do
      resources :posts 
      resources :users
      get '/', to: 'dashboards#index'
      concern :paginatable do
        get '(page/:page)', action: :index, on: :collection, as: ''
      end
      resources :products do
            resources :variants 
        end
       
      resources :taxons , concerns: :paginatable
      post '/csv/create_post', to: 'csv#create_post'
      post '/csv/create_product', to: 'csv#create_product'
      # resources :variants 
    end
    root "homes#index"
    resources :posts 
  end
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/taxon.rb
# == Schema Information
#
# Table name: taxons
#
#  id               :integer          not null, primary key
#  meta_description :string
#  meta_title       :string
#  name             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Taxon < ApplicationRecord
    has_and_belongs_to_many :products,join_table: 'products_taxons'
    has_many :pictures
end

app/controllers/admin/taxons_controller.rb
class Admin::TaxonsController < ApplicationController
        include ApplicationHelper
        layout :dynamic_layout
        before_action :check_link
        before_action :set_taxon, only: %i[ show edit update destroy ]
        # GET /products or /products.json
        def index
          @search = Taxon.ransack(params[:q])
          @taxons = @search.result
          @taxons= @taxons.page(params[:page]).per(10)
          
        end
      
        # GET /products/1 or /products/1.json
        def show
        end
      
        # GET /products/new
        def new
          @taxon = Taxon.new
        end
      
        # GET /products/1/edit
        def edit
        end
      
        # POST /products or /products.json
        def create
          @taxon = Taxon.new(taxon_params)
          respond_to do |format|
            if @taxon.save
              format.html { redirect_to admin_taxons_path, notice: "Product was successfully created." }
              format.json { render :show, status: :created, location: @product }
            else
              format.html { render :new, status: :unprocessable_entity }
              format.json { render json: @taxon.errors, status: :unprocessable_entity }
            end
          end
        end
      
        # PATCH/PUT /products/1 or /products/1.json
        def update
          respond_to do |format|
            if @taxon.update(taxon_params)
              format.html { render :show, notice: "Product was successfully updated." }
              format.json { render :show, status: :ok, location: @taxon }
            else
              format.html { render :edit, status: :unprocessable_entity }
              format.json { render json: @taxon.errors, status: :unprocessable_entity }
            end
          end
        end
      
        # DELETE /products/1 or /products/1.json
        def destroy
          @taxon.destroy
      
          respond_to do |format|
            format.html { redirect_to admin_taxons_path, notice: "Product was successfully destroyed." }
            format.json { head :no_content }
          end
        end
      
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_taxon
            @taxon = Taxon.find(params[:id])
          end
         
      
          # Only allow a list of trusted parameters through.
          def taxon_params
            params.require(:taxon).permit(:name, :meta_title, :meta_description)
          end
end
      

app/controllers/taxons_controller.rb
class TaxonsController < ApplicationController
    skip_before_action :authenticate_user!,  only: %i[ show index]
    before_action :set_taxon, only: %i[ show]
    def index
        @taxons= Taxon.all
    end
    def show
       @taxons = Taxon.limit(12)
       @products = @taxon.products
    end
    private
        def set_taxon
        @taxon = Taxon.find(params[:id])
        end
    
end

app/helpers/taxons_helper.rb
module TaxonsHelper
end

app/views/admin/taxons/_form.html.erb
<%= form_with(model: [:admin,taxon], local: true) do |form| %>
<% if taxon.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(taxon.errors.count, "error") %> prohibited this taxon from being saved:</h2>

  <ul>
    <% taxon.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

<div class="field">
  <%= form.label :meta_title %>
  <%= form.text_field :meta_title %>
</div>

<div class="field">
  <%= form.label :meta_title %>
  <%= form.text_field :meta_title %>
</div>

<div class="field">
  <%= form.label :meta_description %>
  <%= form.text_area :meta_description %>
</div>
<div class="actions">
  <%= form.submit %>
</div>

<% end %>

app/views/admin/taxons/index.html.erb
<div class = "d-flex  form_search pb-3">
<%= search_form_for [:admin,@search], class: "form-inline" do |f| %>
	<div class="form-group">
        <%= f.text_field :name_cont, class: "form-control" %><br>
    </div> <!-- Tìm kiếm theo name có chứa ... -->
    <%= f.submit 'Search', class: "btn btn-default" %>
<% end %>
<%= link_to 'New Taxon', new_admin_taxon_path,class: "btn btn-success text-white" ,id:"new_taxon"  %>
</div>
<table class="table table-bordered table-dark">
  <thead>
    <tr>
      <th scope="col"><%=t ("name") %></th>
      <th scope="col"><%=t ("meta_title") %></th>
      <th scope="col"><%=t ("meta_description") %></th>
      <th colspan="3"><%=t ("actions") %></th>
    </tr>
  </thead>

  <tbody>
  <%= paginate @taxons, theme: 'twitter-bootstrap-3' %>
    <% @taxons.each do |taxon| %>
      <tr>
        <td><%= taxon.name %></td>
        <td><%= taxon.meta_title %></td>
        <td><%= taxon.meta_description %></td>
        <td><%= link_to 'Edit', edit_admin_taxon_path(taxon) ,:class => "btn btn-success text-white" %></td>
        <td><%= button_to 'Destroy', admin_taxon_path(taxon), method: :delete, data: { confirm: 'Are you sure?' },:class  => "btn btn-danger text-white" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/taxons/new.html.erb
<h1>New Taxon</h1>

<%= render 'form', taxon: @taxon %>