config/routes.rb
Rails.application.routes.draw do
  resources :products 
  resources :taxons , only: %i[ show index]
  resources :users
  scope "(:locale)", locale: /en|vi/ do
    devise_scope :user  do
      get "user/signin" => "devise/sessions#new"
      post "user/signin" => "devise/sessions#create"
      delete "user/signout" => "devise/sessions#destroy"
    end

    namespace :admin do
      resources :posts 
      resources :users
      get '/', to: 'dashboards#index'
      concern :paginatable do
        get '(page/:page)', action: :index, on: :collection, as: ''
      end
      resources :products do
            resources :variants 
        end
       
      resources :taxons , concerns: :paginatable
      post '/csv/create_post', to: 'csv#create_post'
      post '/csv/create_product', to: 'csv#create_product'
      # resources :variants 
    end
    root "homes#index"
    resources :posts 
  end
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id               :integer          not null, primary key
#  description      :string
#  meta_description :text
#  meta_keywords    :string
#  name             :string           not null
#  pictures         :json
#  price            :string
#  sku              :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Product < ApplicationRecord
    mount_uploaders :pictures, PictureUploader
    serialize :pictures
    has_and_belongs_to_many :taxons,join_table: 'products_taxons'
    has_many :variants

    class << self
        def import file
          products_attributes = []
          CSV.foreach(file.path, headers: true, col_sep: ",", header_converters: :symbol) do |row|
            row = row.to_hash
            Product.create! row 
          end
        end
      end
      
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  include ApplicationHelper
  layout :dynamic_layout
  before_action :set_product, only: %i[ show edit update destroy  ]
  before_action :check_link
  # GET /products or /products.json
  def index
    @search = Product.ransack(params[:q])
    @products = @search.result
    @products= @products.page(params[:page]).per(10)
    
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    
  end


  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { render :show, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { render :show, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_path, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end
   

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :sku, :description, :meta_description, :meta_keywords,:price,{taxon_ids:[]},{pictures:[]},{pictures_attributes: [ :_destroy, :id, :image]})
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    skip_before_action :authenticate_user!,  only: %i[ show index]
    before_action :set_product, only: %i[ show]
    def index
    end
    def show
        @taxons= Taxon.all
    end
   
    private
        def set_product
        @product = Product.find(params[:id])
        end
    
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
  <%= form_with(model: [:admin,product], local: true) do |form| %>
  <div class="row p-5">
  <% if product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
      <% product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="col-5">
      <label>Pictures</label>
      <div>
      <% if product.pictures? %>
      <% product.pictures.each do |p| %>
        <%= image_tag(p.url)  %>
        <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe,"#", method: :delete, data: { confirm: 'Are you sure?'},:remote => true,:class  => "btn btn-danger text-white" %></td>
      <% end %>
      <% end %>
      </div>
    <div class = "pt-5">
    <%= form.file_field :pictures, multiple: true%>
    </div>
  </div>
  <div class="col-7">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :sku %>
      <%= form.text_field :sku %>
    </div>
    <div class="field">
      <%= form.label :price %>
      <%= form.text_field :price %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_field :description %>
    </div>

    <div class="field">
      <%= form.label :meta_description %>
      <%= form.text_area :meta_description %>
    </div>

    <div class="field">
      <%= form.label :meta_keywords %>
      <%= form.text_field :meta_keywords %>
    </div>
    <div class="field">
      <%= form.label :taxon %>
      <%= form.select :taxon_ids,Taxon.all.collect {|s| [s.name, s.id]}, {:include_blank => true} , multiple: true, :size => 5  if Taxon.count > 0 %>
    </div>
    </div>
    <div class="actions w-100 text-center">
      <%= form.submit %>
    </div>
    <% end %>

app/views/admin/products/edit.html.erb
<%= link_to '<i class="fab fa-500px"></i> Variant'.html_safe,admin_product_variants_path(@product),:class  => "btn btn-success text-white" %>
<%= render 'form', product: @product %>

app/views/admin/products/index.html.erb
<div class = "d-flex  form_search">
<%= search_form_for [:admin,@search], class: "form-inline" do |f| %>
	<div class="form-group">
        <%= f.text_field :name_cont, class: "form-control" %><br>
    </div> <!-- Tìm kiếm theo name có chứa ... -->
    <%= f.submit 'Search', class: "btn btn-default" %>
<% end %>
<%= link_to 'New Product', new_admin_product_path,class: "btn btn-success text-white" ,id:"new_product"  %>
</div>
<table class="table table-bordered table-dark">
  <thead>
    <tr>
      <th scope="col"><%=t ("name") %></th>
      <th scope="col"><%=t ("sku") %></th>
      <th scope="col"><%=t ("description") %></th>
      <th scope="col"><%=t ("meta_description") %></th>
      <th scope="col"><%=t ("meta_keywords") %></th>
      <th scope="col"><%=t ("taxons") %></th>
      <th scope="col"><%=t ("picture") %></th>
      <th colspan="3"><%=t ("actions") %></th>
    </tr>
  </thead>

  <tbody class = "product_table">
  <%= paginate @products, theme: 'twitter-bootstrap-3' %>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.name,edit_admin_product_path(product) %></td>
        <td><%= product.sku %></td>
        <td class ="name"><%= product.description %></td>
        <td class ="name"><%= product.meta_description %></td>
        <td><%= product.meta_keywords %></td>
        <td><%= product.taxons.pluck(:name).join(', ')  if product.taxons.present? %></td>
        <td >
        <%if product.pictures? %>
        <div class = "row">
        <%product.pictures.first(6).each do |p| %>
        <%= image_tag p.url ,class: 'list_image col-lg-2 col-3 mb-4'%>
        <% end %>
         </div>
        <% end %>
        </td>
        <td><%= link_to '<i class="far fa-trash-alt"></i> Destroy'.html_safe, admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' },:class  => "btn btn-danger text-white" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<h3>Import Product</h3>
 <%= form_tag admin_csv_create_product_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload Post" %>
<% end %>

<%# <%= link_to 'New Product', new_admin_product_path %> 

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

app/views/admin/products/show.html.erb
<div class="row p-5">
  <div class="col-5">
    <div class="p-3 mb-2">
      <div>
        <strong>Pictures:</strong>

      </div>
      <%if @product.pictures? %>
      <% @product.pictures.each do |p| %>
      <%=image_tag p.url%>
      <% end %>
      <% end%>
    </div>
  </div>
  <div class="col-7">
    <div>
      <p>
        <strong>Name:</strong>
        <%= @product.name %>
      </p>

      <p>
        <strong>Sku:</strong>
        <%= @product.sku %>
      </p>
      <p>
        <strong>Price:</strong>
        <%= @product.price %>
      </p>
      <p>
        <strong>Description:</strong>
        <%= @product.description %>
      </p>

      <p>
        <strong>Meta description:</strong>
        <%= @product.meta_description %>
      </p>

      <p>
        <strong>Meta keywords:</strong>
        <%= @product.meta_keywords %>
      </p>
      <p>
        <strong>Taxons:</strong>
        <%= @product.taxons.pluck(:name).join(",") %>
      </p>

    </div>
  </div>
</div>