config/routes.rb
Rails.application.routes.draw do
  resources :products 
  resources :taxons , only: %i[ show index]
  resources :users
  scope "(:locale)", locale: /en|vi/ do
    devise_scope :user  do
      get "user/signin" => "devise/sessions#new"
      post "user/signin" => "devise/sessions#create"
      delete "user/signout" => "devise/sessions#destroy"
    end

    namespace :admin do
      resources :posts 
      resources :users
      get '/', to: 'dashboards#index'
      concern :paginatable do
        get '(page/:page)', action: :index, on: :collection, as: ''
      end
      resources :products do
            resources :variants 
        end
       
      resources :taxons , concerns: :paginatable
      post '/csv/create_post', to: 'csv#create_post'
      post '/csv/create_product', to: 'csv#create_product'
      # resources :variants 
    end
    root "homes#index"
    resources :posts 
  end
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id               :integer          not null, primary key
#  description      :string
#  meta_description :text
#  meta_keywords    :string
#  name             :string           not null
#  pictures         :json
#  price            :string
#  sku              :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Product < ApplicationRecord
    mount_uploaders :pictures, PictureUploader
    serialize :pictures
    has_and_belongs_to_many :taxons,join_table: 'products_taxons'
    has_many :variants

    class << self
        def import file
          products_attributes = []
          CSV.foreach(file.path, headers: true, col_sep: ",", header_converters: :symbol) do |row|
            row = row.to_hash
            Product.create! row 
          end
        end
      end
      
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  include ApplicationHelper
  layout :dynamic_layout
  before_action :set_product, only: %i[ show edit update destroy  ]
  before_action :check_link
  # GET /products or /products.json
  def index
    @search = Product.ransack(params[:q])
    @products = @search.result
    @products= @products.page(params[:page]).per(10)
    
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    
  end


  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { render :show, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { render :show, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_path, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end
   

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :sku, :description, :meta_description, :meta_keywords,:price,{taxon_ids:[]},{pictures:[]},{pictures_attributes: [ :_destroy, :id, :image]})
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    skip_before_action :authenticate_user!,  only: %i[ show index]
    before_action :set_product, only: %i[ show]
    def index
    end
    def show
        @taxons= Taxon.all
    end
   
    private
        def set_product
        @product = Product.find(params[:id])
        end
    
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_collection_product.html.erb
<section id="collection_index">
    <div class="collect_header">
      <div class="title">
        <h2> <%=link_to taxon.name ,taxon_path(taxon) %> </h2>
      </div>
    </div>
    <div class="collect_taxon">
      <div class="list_product_row row row-cols-5">
        <% products.each do |product|%>
        <div class="product_row col  ">
          <div class = "product-loop ">
             <div class = "product_img"> <%= image_tag product.pictures.first.url,:class => "w-100" if product.pictures? %></div>
              <div class = "product_name"><%=link_to  product.name ,product_path(product), :class => "name"  %></div>
              <div class = "price_row">
                <span class = "product_price"><%= product.price.present? ? number_to_currency(product.price, precision: 0,unit: "₫" ,format: "%n %u") : "&nbsp".html_safe  %></span>
                <span class = "vairiant_price"><%= product.variants.present? ?number_to_currency(product.variants.first.cost_price ,precision: 0,unit: "₫" ,format: "%n %u") :"&nbsp".html_safe %> </span>
                </div>
              <div class = "add_cart">
                 <%= link_to 'Add to Cart',product_path(product) , :class => "btn btn-warning d-flex text-center justify-content-center"%> 
          </div>
          </div>
          
        </div>
        <% end %>
      </div>

    </div>
  </section>

app/views/products/show.html.erb
 <%= render 'homes/header'  %>
<div class="row">
  <div class="col-6">
    <div class="p-3 mb-2">
      <div>
        <strong>Pictures:</strong>

      </div>
      <%if @product.pictures? %>
      <% @product.pictures.each do |p| %>
      <%=image_tag p.url%>
      <% end %>
      <% end%>
    </div>
  </div>
  <div class="col-6">
    <div>
      <p>
        <strong>Name:</strong>
        <%= @product.name %>
      </p>

      <p>
        <strong>Sku:</strong>
        <%= @product.sku %>
      </p>
      <p>
        <strong>Price:</strong>
        <%= number_to_currency(@product.price, precision: 0,unit: "₫" ,format: "%n %u") %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @product.description %>
      </p>

      <p>
        <strong>Meta description:</strong>
        <%= @product.meta_description %>
      </p>

      <p>
        <strong>Meta keywords:</strong>
        <%= @product.meta_keywords %>
      </p>

      <p>
        <strong>Variants:</strong>
        <% @product.variants.each do |variant| %>
        <span><%= radio_button_tag variant.sku, variant.id ,false %><%=variant.sku%></span>
        <% end %>
      </p>

    </div>
    <div class = "d-flex">
   <div class="quantity-area clearfix">
											<input type="button" value="-" class="qty-btn quantity-left-minus">
											<input type="text" id="quantity" name="quantity" value="1" min="1" class="quantity-input">
											<input type="button" value="+" class="qty-btn quantity-right-plus">
										</div>
    <div class="cart_area">
      <%= link_to 'Add to Cart',"#",class: "btn btn-warning btn-add-cart" , data: {name: "#{@product.name}", target: "#modal" }  %>
      <%= link_to 'Buy Now',"#" , :class => "btn btn-danger btn-add-cart "%>
    </div>

    </div>
  </div>
</div>